### ISSUE TITLE
Fails to compile - missing tools, md5

### ISSUE THREAD

**Issue by OPNA2608** [vampirefrog/libdmpfile#1]
https://github.com/vampirefrog/libdmpfile/blob/ded7e388a95a475c49a6701837ac24d6a3db9f17/dmp_file.c#L6
https://github.com/vampirefrog/libdmpfile/blob/ded7e388a95a475c49a6701837ac24d6a3db9f17/dmpdump.c#L4-L5

**Comment by vampirefrog** [comment]
You're right, this is just code branched off from fmtoy, not working yet, will add missing files at some point, I'm glad there is interest in it.

**Comment by vampirefrog** [comment]
compiles now, but it doesn't do much, plus it only supports one version. next step is to get some test files, make a test suite etc. I'll revisit this code when I require DMP file loading and saving in my other projects, thanks for reporting

**Comment by vampirefrog** [comment]
also do you mind if I ask what you need it for? and if you have some .dmp file collection for testing? thanks
